// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkziXdnWnyhEgE3F_SEyNgHQX9hWva-vg',
    appId: '1:481733670920:web:7f3f6efa2fa0b6658d39bd',
    messagingSenderId: '481733670920',
    projectId: 'chat-app-697b7',
    authDomain: 'chat-app-697b7.firebaseapp.com',
    storageBucket: 'chat-app-697b7.appspot.com',
    measurementId: 'G-WGYYKHYPML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB85edCGRCCRDuBeG4lpbUIcSIkUP2FzyA',
    appId: '1:481733670920:android:c857b4e154bf1aa28d39bd',
    messagingSenderId: '481733670920',
    projectId: 'chat-app-697b7',
    storageBucket: 'chat-app-697b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1uZ7UWkYDHbAFgu0rC7kq7vZ-5Zso_w',
    appId: '1:481733670920:ios:c049a1b047e5ee078d39bd',
    messagingSenderId: '481733670920',
    projectId: 'chat-app-697b7',
    storageBucket: 'chat-app-697b7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1uZ7UWkYDHbAFgu0rC7kq7vZ-5Zso_w',
    appId: '1:481733670920:ios:a5e6954755d568f68d39bd',
    messagingSenderId: '481733670920',
    projectId: 'chat-app-697b7',
    storageBucket: 'chat-app-697b7.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
